# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SupportRecuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('srok', models.DateField()),
                ('desc', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Status')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Tema')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AddField(
            model_name='supportrecuest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Tip'),
        ),
        migrations.AddField(
            model_name='supportrecuest',
            name='vajnost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Vajnost'),
        ),
        migrations.AddField(
            model_name='message',
            name='support_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.SupportRecuest'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
