# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrecuest',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
