# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20160521_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='support_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.SupportRecuest', unique=True),
        ),
    ]
