# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20160601_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otdel',
            name='configuration_1c',
        ),
        migrations.AddField(
            model_name='otdel',
            name='configuration_1c',
            field=models.ManyToManyField(blank=True, to='proposal.ConfugurationOneC'),
        ),
        migrations.RemoveField(
            model_name='supportrecuest',
            name='configuration_1c',
        ),
        migrations.AddField(
            model_name='supportrecuest',
            name='configuration_1c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.ConfugurationOneC'),
        ),
    ]
